# Generated by Django 4.2 on 2023-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tutor', '0002_alter_mentor_user_alter_student_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(default='profile/default-avatar.png', upload_to='profile'),
        ),
    ]
