# Generated by Django 4.2 on 2023-04-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_tutor', '0002_mentor'),
        ('online_tutor', '0002_student'),
    ]

    operations = [
    ]
